# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a83853d7510447cfb7790a2d55cca7bffb10ba1229712079ae7fe5effb8d72d55e29d3645010f41f4fc65070909b24f41a63d555de20d29ca52b96798753542

test:
  secret_key_base: a5bc4e4af1e1dfda5bad91e27e4a07db10670c11550a68db4de57ac7b3f3f71da58d6eb9125c683a74b05c4230808f46f8e6297573e996f234e71460303e821e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
